<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2024/10/16 19:49:56

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=gestion_usuarios',
  'username' => 'postgres',
  'password' => 123,
  'name' => 'doctrine',
)),);
